### PR TITLE
Stretch Gazebo for ROS1

### PR DESCRIPTION
**Pull request by vatanaksoytezer**
Ongoing PR to achieve a fully working Stretch on Gazebo

### CODE REVIEW

**Comment by vatanaksoytezer** [comment]
This should fully work now including all the sensors and actuators. I might want to tune the physics a little bit more, but as an initial work this should do the trick. I will squash this and will check the dependencies, then it will be ready to merge.

**Comment by vatanaksoytezer** [comment]
I documented, cleaned up, squashed and rebased this. @hello-binit this is ready for it's initial merge now. I would appreciate if I can get a review.

**Comment by hello-binit** [comment]
Thanks @vatanaksoytezer, excited to test out the simulation. Currently running up against the following two issues when trying to build the package:
1. Rosdep is unable to resolve `realsense_gazebo_plugin`
2. `catkin_make` fails with the following error:
```
-- +++ processing catkin package: 'stretch_gazebo'
-- ==> add_subdirectory(stretch_ros/stretch_gazebo)
CMake Error at /opt/ros/melodic/share/catkin/cmake/custom_install.cmake:13 (_install):
  _install FILES given directory "config" to install.
Call Stack (most recent call first):
  stretch_ros/stretch_gazebo/CMakeLists.txt:8 (install)
```

Have you seen either of these error before?

**Comment by vatanaksoytezer** [comment]
Hey @hello-binit I am Out of office today but here are quick ways you should be able to get it working: 

1) clone realsense gazebo plugin to your workspace
2) delete config install from strecth gazebo.

I'll apply these fixes to this pr in the weekend

**Comment by hello-binit** [comment]
Thanks! Looks good @vatanaksoytezer, I'll merge it in once you've had a chance to solve the realsense gazebo plugin and config install issues.

I'll also add a "Known Limitations" section to the Gazebo README later. For example, it seems the gazebo simulation has three different joint trajectory action controllers, which differs from the single controller `stretch_core` uses.

**Comment by vatanaksoytezer** [comment]
https://github.com/PickNikRobotics/stretch_ros/pull/45/ here is the PR for ignition port and documentation @hello-binit

**Pull request merged**
