### PR TITLE
RTAB Config

### PR DESCRIPTION
**Pull request by NateWright**
I got RTAB running on real robot and gazebo. I includes examples. LMK what needs to be changed if interested such as moving rtab files into stretch_navigation. Tested on Noetic should also work on Melodic.

### CODE REVIEW

**Comment by hello-binit** [comment]
@NateWright, thanks for adding support for RTAB-Map! I'll begin testing this and let you know if any changes are required.

**Comment by hello-binit** [comment]
Hi @NateWright, can you include a Apache 2.0 license in the "stretch_rtab" package added in this PR? You can [copy it from](https://github.com/hello-robot/stretch_ros/blob/dev/noetic/stretch_navigation/LICENSE.md) "stretch_navigation". This allows others to use and build on your work when we've merged this in.

You don't need to rebase from upstream, I've sorted out the merge in this branch: [feature/rtab_pr_merge](https://github.com/hello-robot/stretch_ros/tree/feature/rtab_pr_merge).

**Comment by NateWright** [comment]
@hello-binit I have added the license to my repo

**Comment by hello-binit** [comment]
@NateWright the PR is merged! Thanks again!

**Comment by hello-binit** [comment]
@NateWright, I'd like to highlight your work in this PR on our forum/twitter. I think the community would find the new mapping packages useful. I'm starting to prepare docs and collect GIFs. Would you be fine with me acknowledging your contributions in these posts?

**Comment by NateWright** [comment]
I give you my permission. @hello-binit

**Pull request merged**
