### PR TITLE
Bugfix/rtabmap

### PR DESCRIPTION
**Pull request by NateWright**
Fixed issues with rtabmap config with 3d_unknown

### CODE REVIEW

**Comment by hello-binit** [comment]
Hi @NateWright, thanks for the PR! I was wondering why `d435i_basic.launch` and `d435i_high_resolution.launch` were copied into the stretch_rtabmap package? They look pretty similar to the ones in stretch_core.

**Comment by NateWright** [comment]
The main difference is the realsense package which uses rs_rgbd instead of rs_camera. rs_rgbd creates a depth registered point cloud which I was using for another package alongside rtabmap. I can remove them from the PR if necessary.

**Comment by hello-binit** [comment]
Okay, thanks for the explanation. They can stay in!

**Comment by hello-binit** [comment]
Thanks for the PR again! The rtabmap fixes are merged in.

**Pull request merged**
