### PR TITLE
Fix broken APIs in Command groups after new contact model feature in stretch_body

### PR DESCRIPTION
**Pull request by hello-fazil**
The contact_thresh_N, contact_thresh_pos_N and contact_thresh_neg_N argument is deprecated by removing the suffix '_N' with all the move_to(),move_by(), translate_by() and rotate_by() APIs that is associated with stepper motors after the new contact models feature introduced to the stretch_body.

### CODE REVIEW

**Comment by hello-fazil** [comment]
After this branch merges the above-mentioned API fixes must also be implemented in to the melodic branch.

**Comment by aedsinger** [comment]
See the new API with Stretch Body 0.4.0.dev0

**Comment by hello-binit** [comment]
@hello-fazil @aedsinger Thoughts on adding a version check to Stretch Driver, where if `stretch_body.__version__` is under 0.4.0, it'll error out and ask the user to upgrade?

**Comment by hello-fazil** [comment]
> @hello-fazil @aedsinger Thoughts on adding a version check to Stretch Driver, where if `stretch_body.__version__` is under 0.4.0, it'll error out and ask the user to upgrade?

Yes, I think that would be a good feature.

**Review by hello-binit — APPROVED** [review]
Looks good!

**Pull request merged**
